name: "BackPipeline"

on:
    push:
        branches:
            - "main"

jobs:
  call-workflow-data:
        uses: bryanus1/pipelines-reusable/.github/workflows/publish_docker_image.yaml@main
        with:
          bucket_name: s3-bucket-braves
        secrets:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
